modules:
  prefix: "&b&lEmotes &7»"
  chat-format: true

chat:
  groups:
    default: "{prefix}{name} &7» &f{message}"
    admin: "&e+ {prefix}{name} &7» &f{message}"

display:
  enabled:
    switch: true
    title: "&b&lEmotes"
    subtitle: "&fEmotes have been &aActivated"
    sound: LEVEL_UP:10:2
  disabled:
    switch: true
    title: "&b&lEmotes"
    subtitle: "&fEmotes have been &cDisabled"
    sound: ANVIL_BREAK:10:2

emotes:
  list:
    - "&7&m-------------------------------"
    - ""
    - "  &b&lEmotes &fv1.1 &7| &fList"
    - ""
    - " &7- &b<3 &f= &c❤"
    - " &7- &b:shrug: &f= &e¯\\_(ツ)_/¯"
    - " &7- &b:uwu: &f= &dฅ^•ﻌ•^ฅ"
    - ""
    - " &fPowered by &b&lAquatic Studios"
    - ""
    - "&7&m-------------------------------"

messages:
  disabled: "%prefix% &cYou just disabled chat emotes"
  enabled: "%prefix% &aYou just activated chat emotes"
  reload: "%prefix% &aThe plugin just restarted successfully"
  no_permission: "%prefix% &cYou no have permission to execute this command"
  rank_permission: "%prefix% &cYou need &3[Aquatic] &crank to execute this command, purchase it at &ehttps://discord.gg/qqU3SVwDaT"