modules:
  prefix: "&b&lEmotes &7»"
  emotes: true

chat:
  switch: true
  groups:
    default: "{prefix}{name} &7» &f{message}"
    admin: "&4&lADMIN &f{name} &7» &f{message}"

messages:
  reload: "%prefix% &aThe plugin just restarted successfully"
  error: "%prefix% &cThe command you execute was not found"
  nopermission: "%prefix% &cYou no have permission to execute this command"
  rank_permission: "%prefix% &cYou need &b[Aquatic] &crank to execute this command, purchase it at &ehttps://discord.gg/qqU3SVwDaT"

emotes:
  list:
    - ""
    - "&b&lEmotes &fv1.0 &7| &fList"
    - ""
    - " &7- &b<3 &f- &c❤"
    - " &7- &b:shrug: &f- &e¯\\_(ツ)_/¯"
    - ""